version: '3.8'

services:
  app01:
    image: flask-hostname-app
    platform: linux/amd64
    deploy:
      replicas: 3
    environment:
      - FLASK_DEBUG=false
      - PORT=5000
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge